import { HealthRecord } from './types';

export const MOCK_HEALTH_RECORDS: HealthRecord[] = [
  {
    id: 'rec-1',
    type: 'Lab Report',
    title: 'Complete Blood Count & Pitta Metabolic Panel',
    date: '2026-08-22',
    doctor: 'Dr. Anandita Verma (Pathologist)',
    facility: 'Amrutam Diagnostics Lab',
    notes: 'Hemoglobin (14.6 g/dL) is optimal. Mild Pitta heat detected in liver enzymes (ALT 46 U/L). Recommended cooling herbal decoction.',
    tags: ['Blood Test', 'Pitta Dosha', 'Liver Enzymes'],
    attachments: [
      {
        id: 'att-1',
        name: 'CBC_Pitta_Report.pdf',
        type: 'pdf',
        uri: 'https://images.unsplash.com/photo-1579154204601-01588f351e67?auto=format&fit=crop&w=800&q=80',
        size: '2.4 MB',
      },
      {
        id: 'att-2',
        name: 'Smear_Micrograph.jpg',
        type: 'image',
        uri: 'https://images.unsplash.com/photo-1576086213369-97a306d36557?auto=format&fit=crop&w=800&q=80',
        size: '1.1 MB',
      },
    ],
  },
  {
    id: 'rec-2',
    type: 'Prescription',
    title: 'Triphala & Brahmi Kwatha Protocol',
    date: '2026-08-18',
    doctor: 'Dr. Pooja Sharma (BAMS, MD)',
    facility: 'Amrutam Holistic Clinic',
    notes: 'Prescribed Triphala Churna (500mg twice daily) and Brahmi Ghrita (5ml bedtime) to balance digestive Agni and promote restorative sleep.',
    tags: ['Digestion', 'Pitta Calming', 'Herbal Rx'],
    attachments: [
      {
        id: 'att-3',
        name: 'Prescription_Aug2026.pdf',
        type: 'pdf',
        uri: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=800&q=80',
        size: '1.2 MB',
      },
    ],
  },
  {
    id: 'rec-3',
    type: 'Consultation',
    title: 'Nadi Pariksha & Constitutional Assessment',
    date: '2026-08-10',
    doctor: 'Dr. Rajeshwar Bhatt (Senior Vaidya)',
    facility: 'Amrutam Wellness Clinic',
    notes: '8-fold pulse examination revealed Pitta-Vata dual Prakriti. Patient noted seasonal body heat and scalp dryness. Recommended lifestyle modifications.',
    tags: ['Nadi Pariksha', 'Prakriti', 'Pitta-Vata'],
    attachments: [
      {
        id: 'att-4',
        name: 'Nadi_Pariksha_Chart.jpg',
        type: 'image',
        uri: 'https://images.unsplash.com/photo-1505751172876-fa1923c5c528?auto=format&fit=crop&w=800&q=80',
        size: '1.8 MB',
      },
    ],
  },
  {
    id: 'rec-4',
    type: 'Vaccination',
    title: 'Swarnaprashana Ayurvedic Immunization',
    date: '2026-08-04',
    doctor: 'Dr. Meera Nambiar (Kaumarbhritya)',
    facility: 'Amrutam Care Center',
    notes: 'Purified gold ash (Swarna Bhasma) processed with Brahmi, Vacha, and organic honey administered on Pushya Nakshatra to boost immunity.',
    tags: ['Swarnaprashana', 'Immunity', 'Pushya Nakshatra'],
    attachments: [
      {
        id: 'att-5',
        name: 'Immunization_Card.pdf',
        type: 'pdf',
        uri: 'https://images.unsplash.com/photo-1631217868264-e5b90bb7e133?auto=format&fit=crop&w=800&q=80',
        size: '850 KB',
      },
    ],
  },
  {
    id: 'rec-5',
    type: 'Allergy',
    title: 'Mustard & Raw Sesame Oil Sensitivity',
    date: '2026-07-24',
    doctor: 'Dr. Vikramaditya Sen (Dermatologist)',
    facility: 'Amrutam Skin Care Center',
    notes: 'Severe contact erythema when exposed to raw unboiled mustard oil. Immediate treatment: wash with cold rose water & apply Shatadhauta Ghrita.',
    tags: ['Contact Allergy', 'Skin Reaction', 'Severe'],
    attachments: [
      {
        id: 'att-6',
        name: 'Skin_Patch_Analysis.jpg',
        type: 'image',
        uri: 'https://images.unsplash.com/photo-1588776814546-1ffcf47267a5?auto=format&fit=crop&w=800&q=80',
        size: '1.4 MB',
      },
    ],
  },
  {
    id: 'rec-6',
    type: 'Consultation',
    title: 'Monsoon Regimen (Varsha Ritucharya) Review',
    date: '2026-07-12',
    doctor: 'Dr. Pooja Sharma (BAMS, MD)',
    facility: 'Amrutam Holistic Clinic',
    notes: 'Seasonal review for monsoon care. Advised avoiding heavy sour and fermented items to prevent Pitta accumulation and digestive sluggishness.',
    tags: ['Ritucharya', 'Monsoon Care', 'Diet'],
    attachments: [
      {
        id: 'att-7',
        name: 'Monsoon_Diet_Guide.pdf',
        type: 'pdf',
        uri: 'https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=800&q=80',
        size: '1.5 MB',
      },
    ],
  },
  {
    id: 'rec-7',
    type: 'Lab Report',
    title: 'Lipid Profile & Cholesterol Panel',
    date: '2026-05-15',
    doctor: 'Dr. Suniti Joshi (Biochemist)',
    facility: 'CarePath Diagnostic Center',
    notes: 'Total cholesterol 192 mg/dL (normal), HDL 54 mg/dL. Triglycerides borderline (158 mg/dL). Recommended Guggulu formulation.',
    tags: ['Lipid Profile', 'Cholesterol', 'Routine'],
    attachments: [
      {
        id: 'att-8',
        name: 'Lipid_Panel_Report.pdf',
        type: 'pdf',
        uri: 'https://images.unsplash.com/photo-1579154204601-01588f351e67?auto=format&fit=crop&w=800&q=80',
        size: '1.9 MB',
      },
    ],
  },
  {
    id: 'rec-8',
    type: 'Prescription',
    title: 'Kuntal Hair Revitalizer & Scalp Protocol',
    date: '2026-05-02',
    doctor: 'Dr. Anand Kumar (Trichologist)',
    facility: 'Amrutam Hair & Scalp Clinic',
    notes: 'Prescribed Bhringraj Taila for scalp massage and Kuntal Care Malt (1 tbsp twice daily) for deep follicle rejuvenation.',
    tags: ['Hair Care', 'Bhringraj', 'Scalp Health'],
    attachments: [
      {
        id: 'att-9',
        name: 'Hair_Care_Prescription.pdf',
        type: 'pdf',
        uri: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=800&q=80',
        size: '890 KB',
      },
    ],
  },
  {
    id: 'rec-9',
    type: 'Vaccination',
    title: 'Tetanus Toxoid & Hepatitis Booster',
    date: '2026-03-12',
    doctor: 'Dr. Siddharth Menon (Physician)',
    facility: 'City Health Clinic',
    notes: 'Routine adult tetanus and hepatitis booster administered intramuscularly in left deltoid. No adverse effects observed.',
    tags: ['Tetanus', 'Hepatitis', 'Booster'],
    attachments: [
      {
        id: 'att-10',
        name: 'Vaccination_Card.jpg',
        type: 'image',
        uri: 'https://images.unsplash.com/photo-1631217868264-e5b90bb7e133?auto=format&fit=crop&w=800&q=80',
        size: '1.2 MB',
      },
    ],
  },
  {
    id: 'rec-10',
    type: 'Allergy',
    title: 'Spring Pollen & Wild Honey Sensitivity',
    date: '2026-02-18',
    doctor: 'Dr. Arvind Sharma (Allergist)',
    facility: 'Apex Allergy Center',
    notes: 'Seasonal allergic rhinitis triggered by birch tree pollen and unpasteurized raw forest honey. Advised Sitopaladi Churna.',
    tags: ['Pollen', 'Honey', 'Seasonal'],
    attachments: [
      {
        id: 'att-11',
        name: 'Pollen_IgE_Report.pdf',
        type: 'pdf',
        uri: 'https://images.unsplash.com/photo-1579154204601-01588f351e67?auto=format&fit=crop&w=800&q=80',
        size: '2.1 MB',
      },
    ],
  },
  {
    id: 'rec-11',
    type: 'Prescription',
    title: 'Ashwagandha & Shankhpushpi Rejuvenation',
    date: '2025-11-20',
    doctor: 'Dr. Pooja Sharma (BAMS, MD)',
    facility: 'Amrutam Holistic Clinic',
    notes: 'Winter rejuvenation protocol (Hemanta Rasayana). Shankhpushpi syrup (10ml) and pure Ashwagandha churna (3g with warm milk) for deep sleep and stress relief.',
    tags: ['Ashwagandha', 'Sleep Care', 'Rasayana'],
    attachments: [
      {
        id: 'att-12',
        name: 'Rasayana_Protocol.pdf',
        type: 'pdf',
        uri: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=800&q=80',
        size: '780 KB',
      },
    ],
  },
];
