import { Product } from '@features/shop/types';

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'prod-1',
    name: 'Amrutam Kuntal Care Hair Spa',
    subtitle: 'Herbal Hair Therapy with Neem & Eucalyptus',
    category: 'Hair Care',
    price: 649,
    originalPrice: 899,
    discountPercentage: 28,
    rating: 4.9,
    reviewCount: 380,
    imageUrl: 'https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?auto=format&fit=crop&w=400&q=80',
    badge: 'Bestseller',
    inStock: true,
    volume: '200 ml',
    keyIngredients: ['Bhringraj', 'Neem', 'Eucalyptus', 'Triphala'],
    benefits: [
      'Controls severe dandruff & flaky scalp',
      'Nourishes dry roots with natural herbal lipids',
      'Infuses scalp with cooling calming sensation',
    ],
    description:
      'Amrutam Kuntal Care Hair Spa is a pure Ayurvedic formulation revitalizing damaged hair cuticles. Prepared with classical decoction methods, it balances Pitta dosha in the scalp.',
    dosage:
      'Apply generously from roots to tips on damp hair. Leave for 15-20 minutes and rinse with lukewarm water.',
    doshaSuitability: ['Pitta', 'Vata'],
  },
  {
    id: 'prod-2',
    name: 'Amrutam Bhringraj Hair Oil',
    subtitle: '100% Classical Herbal Scalp Elixir',
    category: 'Hair Care',
    price: 499,
    originalPrice: 650,
    discountPercentage: 23,
    rating: 4.8,
    reviewCount: 512,
    imageUrl: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=400&q=80',
    badge: '100% Organic',
    inStock: true,
    volume: '100 ml',
    keyIngredients: ['Bhringraj', 'Amla', 'Brahmi', 'Nagarmotha'],
    benefits: [
      'Promotes dense hair follicle regrowth',
      'Delays premature greying naturally',
      'Relieves stress & calms nervous system',
    ],
    description:
      'Prepared through ancient Kshirapak Vidhi (milk-decoction process), Bhringraj Taila penetrates the deep dermal layers of the scalp to nourish hair roots from within.',
    dosage:
      'Gently massage into scalp using fingertips in circular motions before sleep or 1 hour prior to hair wash.',
    doshaSuitability: ['Pitta', 'Vata', 'Kapha'],
  },
  {
    id: 'prod-3',
    name: 'Kumkumadi Tailam Radiant Glow',
    subtitle: 'Pure Saffron & Red Sandalwood Night Serum',
    category: 'Skin Care',
    price: 999,
    originalPrice: 1499,
    discountPercentage: 33,
    rating: 5.0,
    reviewCount: 420,
    imageUrl: 'https://images.unsplash.com/photo-1601049541289-9b1b7bbbfe19?auto=format&fit=crop&w=400&q=80',
    badge: 'Luxury Ayurveda',
    inStock: true,
    volume: '30 ml',
    keyIngredients: ['Kashmiri Saffron', 'Red Sandalwood', 'Lotus Stamen', 'Manjistha'],
    benefits: [
      'Restores luminous natural golden complexion',
      'Reduces pigmentation, sun spots & acne scars',
      'Provides intense antioxidant cellular hydration',
    ],
    description:
      'Formulated strictly according to Ashtanga Hridaya, this miraculous Ayurvedic beauty nectar contains pure grade-A Kashmiri saffron and 26 precious Himalayan herbs.',
    dosage:
      'Take 3-4 drops onto palms, warm between hands and press gently onto clean face & neck before sleeping.',
    doshaSuitability: ['Vata', 'Pitta'],
  },
  {
    id: 'prod-4',
    name: 'Amrutam Zeo Malt for Digestion',
    subtitle: 'Ayurvedic Gut Healer & Acidity Relief',
    category: 'Digestive',
    price: 549,
    originalPrice: 699,
    discountPercentage: 21,
    rating: 4.8,
    reviewCount: 290,
    imageUrl: 'https://images.unsplash.com/photo-1571781926291-c477ebfd024b?auto=format&fit=crop&w=400&q=80',
    badge: 'Fast Relief',
    inStock: true,
    volume: '400 g',
    keyIngredients: ['Amaltas', 'Haritaki', 'Saunf', 'Draksha'],
    benefits: [
      'Alleviates chronic acidity, bloating & gas',
      'Strengthens Jatharagni (digestive fire)',
      'Gentle natural overnight bowel cleansing',
    ],
    description:
      'A delicious herbal malt formulated to soothe hyperacidity, gastric ulcers, and irregular bowel movements. Packed with natural digestive enzymes.',
    dosage:
      '1 to 2 tablespoons with warm milk or lukewarm water twice a day after meals.',
    doshaSuitability: ['Pitta', 'Kapha'],
  },
  {
    id: 'prod-5',
    name: 'Amrutam Nari Sondarya Malt',
    subtitle: 'Holistic Reproductive & Hormonal Tonic',
    category: 'Immunity',
    price: 799,
    originalPrice: 1100,
    discountPercentage: 27,
    rating: 4.9,
    reviewCount: 610,
    imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=400&q=80',
    badge: 'Popular',
    inStock: true,
    volume: '400 g',
    keyIngredients: ['Shatavari', 'Ashoka', 'Lodhra', 'Gokshura'],
    benefits: [
      'Balances female hormones & supports regular cycles',
      'Enhances natural stamina & fights fatigue',
      'Nourishes skin glow & hair health from within',
    ],
    description:
      'A comprehensive Ayurvedic rejuvenator for women. Harnesses classical Rasayana herbs like Shatavari and Ashoka to restore natural vitality.',
    dosage:
      '1 tablespoon twice daily with warm milk or water on an empty stomach or before meals.',
    doshaSuitability: ['Vata', 'Pitta', 'Kapha'],
  },
  {
    id: 'prod-6',
    name: 'Ashwagandha Gold Vitality Tablets',
    subtitle: 'Standardized Withanolides for Stress & Energy',
    category: 'Stress & Sleep',
    price: 449,
    originalPrice: 599,
    discountPercentage: 25,
    rating: 4.7,
    reviewCount: 340,
    imageUrl: 'https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?auto=format&fit=crop&w=400&q=80',
    badge: 'Stress Relief',
    inStock: true,
    volume: '60 Tablets',
    keyIngredients: ['Organic Ashwagandha Extract', 'Safed Musli', 'Shilajit'],
    benefits: [
      'Reduces cortisol levels & anxiety naturally',
      'Improves deep REM sleep quality',
      'Boosts physical endurance & muscle recovery',
    ],
    description:
      'Potent adaptogenic formula that shields the body against oxidative stress while sharpening cognitive focus and physical stamina.',
    dosage:
      '1 tablet twice a day with warm water or milk after breakfast and dinner.',
    doshaSuitability: ['Vata', 'Kapha'],
  },
  {
    id: 'prod-7',
    name: 'Orthokey Gold Joint Care Oil',
    subtitle: 'Herbal Pain Reliever with Mahanarayan Taila',
    category: 'Joint Care',
    price: 599,
    originalPrice: 799,
    discountPercentage: 25,
    rating: 4.8,
    reviewCount: 275,
    imageUrl: 'https://images.unsplash.com/photo-1616949755610-8c9bbc08f138?auto=format&fit=crop&w=400&q=80',
    badge: 'Quick Action',
    inStock: true,
    volume: '150 ml',
    keyIngredients: ['Gandhapura', 'Mahanarayan Taila', 'Shallaki', 'Eucalyptus'],
    benefits: [
      'Fast relief from knee, back & neck stiffness',
      'Improves joint lubrication & flexibility',
      'Reduces inflammatory swelling naturally',
    ],
    description:
      'A deeply penetrating pain relief oil powered by classical analgesic herbs. Restores range of motion and eases muscular spasms.',
    dosage:
      'Apply warm oil over affected joints and gently massage for 5-10 minutes. Repeat twice daily.',
    doshaSuitability: ['Vata', 'Kapha'],
  },
  {
    id: 'prod-8',
    name: 'Amrutam Ashtagandh Body Cleanser',
    subtitle: 'Handcrafted Herbal Ubtan with Turmeric & Sandalwood',
    category: 'Skin Care',
    price: 399,
    originalPrice: 499,
    discountPercentage: 20,
    rating: 4.9,
    reviewCount: 195,
    imageUrl: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=400&q=80',
    badge: 'Pure Herbs',
    inStock: true,
    volume: '200 g',
    keyIngredients: ['Kasturi Manjal', 'Chandan', 'Multani Mitti', 'Rose Petals'],
    benefits: [
      'Gently exfoliates dead skin cells without stripping natural oils',
      'Antimicrobial protection against body acne',
      'Leaves skin soft, refreshed & naturally fragrant',
    ],
    description:
      'An authentic Ayurvedic Snana Choornam (bath powder) replacing harsh chemical soaps with grounding herbal aromas.',
    dosage:
      'Mix 2 scoops with water or rose water to form a smooth paste. Massage onto wet skin and rinse.',
    doshaSuitability: ['Pitta', 'Kapha', 'Vata'],
  },
];
