import { Doctor } from '@features/consultation/types';

export const MOCK_DOCTORS: Doctor[] = [
  {
    id: 'doc-1',
    name: 'Dr. Pooja Sharma',
    degree: 'BAMS, MD (Ayurveda)',
    specialties: ['Panchakarma', 'Digestive Health', 'Dosha Balancing'],
    experienceYears: 12,
    rating: 4.9,
    reviewCount: 342,
    consultationFee: 799,
    languages: ['English', 'Hindi'],
    avatarUrl: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&w=400&q=80',
    availability: 'Available Today',
    isVerified: true,
    about: 'Senior Ayurvedic Consultant with extensive experience in chronic metabolic disorders and Panchakarma therapies.',
  },
  {
    id: 'doc-2',
    name: 'Dr. Rajeshwar Iyer',
    degree: 'BAMS, Ph.D in Kayachikitsa',
    specialties: ['Kayachikitsa', 'Immunity & Rasayana', 'Stress Management'],
    experienceYears: 18,
    rating: 4.8,
    reviewCount: 520,
    consultationFee: 1200,
    languages: ['English', 'Hindi', 'Tamil'],
    avatarUrl: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&w=400&q=80',
    availability: 'Next Slot: 4:30 PM',
    isVerified: true,
    about: 'Renowned expert in Rasayana therapy, autoimmune rejuvenation, and chronic lifestyle disorder reversal.',
  },
  {
    id: 'doc-3',
    name: 'Dr. Ananya Joshi',
    degree: 'BAMS, Fellowship in Ayurvedic Dermatology',
    specialties: ['Skin & Hair', 'Psoriasis', 'Acne Care'],
    experienceYears: 9,
    rating: 4.9,
    reviewCount: 280,
    consultationFee: 699,
    languages: ['English', 'Hindi', 'Marathi'],
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=400&q=80',
    availability: 'Available Today',
    isVerified: true,
    about: 'Specialized in natural skin microbiome rejuvenation, Ayurvedic derma treatments, and hair nourishment.',
  },
  {
    id: 'doc-4',
    name: 'Dr. Vikramaditya Vaidya',
    degree: 'BAMS, MD (Dravyaguna)',
    specialties: ['Herbal Formulations', 'Joint & Spine Care', 'Arthritis'],
    experienceYears: 15,
    rating: 4.7,
    reviewCount: 410,
    consultationFee: 950,
    languages: ['English', 'Hindi', 'Gujarati'],
    avatarUrl: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&w=400&q=80',
    availability: 'Available Tomorrow',
    isVerified: true,
    about: 'Expert herbalist and practitioner focusing on musculoskeletal therapies, spine wellness, and herbal synergies.',
  },
  {
    id: 'doc-5',
    name: 'Dr. Gayatri Devi',
    degree: 'BAMS, MS (Ayurvedic Gynaecology - Prasuti Tantra)',
    specialties: ["Women's Health", 'PCOS/PCOD', 'Fertility Care'],
    experienceYears: 14,
    rating: 5.0,
    reviewCount: 490,
    consultationFee: 1100,
    languages: ['English', 'Hindi', 'Telugu'],
    avatarUrl: 'https://images.unsplash.com/photo-1651008376811-b90baee60c1f?auto=format&fit=crop&w=400&q=80',
    availability: 'Available Today',
    isVerified: true,
    about: 'Holistic reproductive health specialist focused on hormonal harmony through diet, yoga, and classical herbal regimens.',
  },
  {
    id: 'doc-6',
    name: 'Dr. Harish Chandra',
    degree: 'BAMS, Nadi Pariksha Specialist',
    specialties: ['Nadi Pariksha (Pulse Diagnosis)', 'Vata Disorders', 'Insomnia'],
    experienceYears: 22,
    rating: 4.9,
    reviewCount: 650,
    consultationFee: 1500,
    languages: ['English', 'Hindi', 'Kannada'],
    avatarUrl: 'https://images.unsplash.com/photo-1582750433449-648ed127bb54?auto=format&fit=crop&w=400&q=80',
    availability: 'Next Slot: 6:00 PM',
    isVerified: true,
    about: 'Master pulse diagnostician with over two decades of experience balancing tri-dosha constitutions.',
  },
];
